// <auto-generated />
using IdentityApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230908141717_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("IdentityApp.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = "01H9T4G7T25PPF0DMY6DMHWCDT",
                            Age = 26,
                            Name = "Ervin K. Cole",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = "01H9T4GARX3V9F02WSQJKTPP3H",
                            Age = 31,
                            Name = "Sara B. Welker",
                            Position = "Software Developer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
